# pubspec.yaml

name: fotolista_gpt
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-pre.1 <=4.0.0"


dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.1.0
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.8.1
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1

  
  firebase_messaging: ^16.0.4
  firebase_storage: ^13.0.4
  
  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.4.1
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  #flutter_riverpod: ^3.0.3
  flutter_slidable: ^4.0.3
  flutter_speed_dial: ^7.0.0
  google_mlkit_text_recognition: ^0.15.0
  google_sign_in: ^7.2.0
  image: ^4.5.4
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  local_auth: ^2.1.6        # No modificar es 2.1.6
  mobile_scanner: ^7.1.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  qr_flutter: ^4.1.0
  #riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3
  speech_to_text: ^7.3.0
  timezone: ^0.10.1
  uuid: ^4.5.2


  #cupertino_icons: ^1.0.8
  #firebase_core: ^2.27.0      
  #firebase_auth: ^4.19.0       
  #google_sign_in: ^6.2.1       
  #cloud_firestore: ^4.15.0     
  #firebase_storage: ^11.6.0
  #image_picker: ^1.2.0
  #uuid: ^4.5.1
  #qr_flutter: ^4.1.0
  #permission_handler: ^12.0.1
  #mobile_scanner: ^7.1.2
  #flutter_image_compress: ^2.4.0
  #cached_network_image: ^3.4.1
  #dynamic_color: ^1.8.1
  #flutter_cache_manager: ^3.4.1
  #path_provider: ^2.1.5
  #google_mlkit_text_recognition: ^0.15.0
  #flutter_slidable: ^4.0.3
  #flutter_speed_dial: ^7.0.0
  #speech_to_text: ^7.3.0
  #image_cropper: ^11.0.0
  #firebase_messaging: ^14.8.0
  #flutter_local_notifications: ^19.4.2
  #timezone: ^0.10.1
  #image: ^4.5.4
  #local_auth: ^2.1.6
  #intl: ^0.20.2
  #shared_preferences: ^2.5.3
  
  # ðŸ‘‡ GESTIÃ“N DE ESTADO CON RIVERPOD (Tema 2)
  #flutter_riverpod: ^2.5.1
  #riverpod_annotation: ^2.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ðŸ‘‡ GENERACIÃ“N DE CÃ“DIGO (Riverpod/Build Runner)
  # Usamos versiones especÃ­ficas para resolver conflictos con build_runner
  #build_runner: ^2.4.9           
  #riverpod_generator: ^3.0.3   # Downgrade sugerido por el error
  #custom_lint: ^0.8.0          # Upgrade sugerido por el error
  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  
  
 


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/carro_compra.png

flutter_localizations:
  sdk: flutter


# pubspec.yaml

# ðŸŽ¯ CONFIGURACIÃ“N DEL ICONO DE LA APLICACIÃ“N
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/carro_compra.png" # â¬…ï¸ Usa la ruta que confirmaste
  min_sdk_android: 21 # Para compatibilidad (generalmente el valor por defecto)